# -*- coding: utf-8 -*-
"""monthly_auto_updater.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqm3USxdnErztsOtyVD04aSwas1ttk89
"""

import os
import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
import warnings

# Suppress warnings for cleaner server logs
warnings.filterwarnings('ignore')

def run_monthly_pipeline(new_data_csv, model_dir, text_column='Commentaire client'):
    """
    Reads new monthly data, categorizes it, and auto-merges new topics if anomalies are detected.
    """
    print(f"--- Starting Topic Pipeline for {new_data_csv} ---")

    # 1. Load the new data
    try:
        df_new = pd.read_csv(new_data_csv)
        df_clean = df_new.dropna(subset=[text_column]).copy()
        new_docs = df_clean[text_column].astype(str).tolist()
    except Exception as e:
        print(f"❌ Error loading data: {e}")
        return False

    # 2. Load the Baseline Model
    print("Loading the master BERTopic model...")
    base_model = BERTopic.load(model_dir)

    # 3. Classify new data (Transformation)
    print("Classifying new comments...")
    new_topics, _ = base_model.transform(new_docs)

    # Map names and save categorized data for the dashboard
    assigned_names = [base_model.custom_labels_[t + base_model._outliers] for t in new_topics]
    df_clean['Assigned_Topic_ID'] = new_topics
    df_clean['Assigned_Topic_Name'] = assigned_names

    output_filename = f"categorized_{os.path.basename(new_data_csv)}"
    df_clean.to_csv(output_filename, index=False)
    print(f"✅ Categorized data saved to {output_filename}")

    # 4. Anomaly Detection (Concept Drift)
    outlier_texts = [new_docs[i] for i in range(len(new_docs)) if new_topics[i] == -1]
    outlier_percentage = (len(outlier_texts) / len(new_docs)) * 100
    print(f"System Health Check - Outlier Rate: {outlier_percentage:.1f}%")

    # 5. Auto-Update Logic
    if outlier_percentage > 20.0 and len(outlier_texts) >= 15:
        print("⚠️ High anomaly rate detected. Initiating Auto-Merge Sequence...")

        # Train a mini-model exclusively on the unrecognized data
        print("Training mini-model on unrecognized comments...")
        embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
        mini_model = BERTopic(embedding_model=embedding_model, min_topic_size=10, language="multilingual")
        mini_model.fit(outlier_texts)

        # Auto-name the new clusters
        new_topic_info = mini_model.get_topic_info()
        mini_custom_labels = {}
        for index, row in new_topic_info.iterrows():
            topic_id = row['Topic']
            if topic_id != -1:
                top_words = [word for word, score in mini_model.get_topic(topic_id)[:3]]
                auto_name = " / ".join(top_words)
                mini_custom_labels[topic_id] = auto_name
                print(f"   -> Discovered new topic: [{auto_name}]")

        mini_model.set_topic_labels(mini_custom_labels)

        # Merge into the master model
        print("Stitching new topics into the Master Model...")
        updated_master_model = BERTopic.merge_models([base_model, mini_model])

        # Overwrite the old model with the new, smarter one
        updated_master_model.save(model_dir, serialization="safetensors")
        print("✅ Master Model successfully updated with new business trends.")
    else:
        print("✅ Data is stable. No model update required.")

    return True

if __name__ == "__main__":
    # --- SERVER CONFIGURATION ---
    # The DevOps/Backend team will update these paths to match the server structure
    DATA_FILE = "path/to/this_months_data.csv"
    MODEL_DIRECTORY = "./export/algerie_telecom_bertopic"

    # run_monthly_pipeline(DATA_FILE, MODEL_DIRECTORY)