# -*- coding: utf-8 -*-
"""topic_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqm3USxdnErztsOtyVD04aSwas1ttk89
"""

import pandas as pd
from bertopic import BERTopic

def rename_topic(model_dir, topic_id, new_name):
    """
    Safely edits a specific topic's business name within a saved BERTopic model.
    Returns True if successful, False if the topic does not exist.
    """
    print(f"Loading master model from {model_dir}...")
    try:
        topic_model = BERTopic.load(model_dir)
    except Exception as e:
        print(f"❌ Error loading model: {e}")
        return False

    # 1. Rebuild the current custom labels dictionary safely
    topic_info = topic_model.get_topic_info()
    current_labels = {}

    for index, row in topic_info.iterrows():
        t_id = row['Topic']
        if 'CustomName' in topic_info.columns and pd.notna(row['CustomName']):
            current_labels[t_id] = row['CustomName']
        else:
            current_labels[t_id] = row['Name']

    # 2. Validate Topic ID
    if topic_id not in current_labels:
        print(f"❌ Error: Topic ID {topic_id} does not exist.")
        return False

    # 3. Update the dictionary
    old_name = current_labels[topic_id]
    current_labels[topic_id] = new_name
    print(f"Renaming Topic {topic_id}: '{old_name}' -> '{new_name}'")

    # 4. Apply and Save
    topic_model.set_topic_labels(current_labels)
    topic_model.save(model_dir, serialization="safetensors")

    print("✅ Model successfully updated with the new business name.")
    return True

if __name__ == "__main__":
    # --- API TESTING CONFIGURATION ---
    MODEL_DIRECTORY = "./export/algerie_telecom_bertopic"

    # Example test variables (Backend will pass these dynamically from the API)
    # TEST_TOPIC_ID = 8
    # TEST_NEW_NAME = "5G Hardware Issues"

    # rename_topic(MODEL_DIRECTORY, TEST_TOPIC_ID, TEST_NEW_NAME)